# Generated by Django 3.0.4 on 2020-03-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsmodel',
            name='password',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='formsmodel',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
